export const DEGREES = {
  white: {
    0: "Nenhum grau",
    1: "1 Grau",
    2: "2 Graus",
    3: "3 Graus",
    4: "4 Graus",
  },
  blue: {
    0: "Nenhum grau",
    1: "1 Grau",
    2: "2 Graus",
    3: "3 Graus",
    4: "4 Graus",
  },
  purple: {
    0: "Nenhum grau",
    1: "1 Grau",
    2: "2 Graus",
    3: "3 Graus",
    4: "4 Graus",
  },
  brown: {
    0: "Nenhum grau",
    1: "1 Grau",
    2: "2 Graus",
    3: "3 Graus",
    4: "4 Graus",
  },
  black: {
    0: "Nenhum grau",
    1: "1 Grau",
    2: "2 Graus",
    3: "3 Graus",
    4: "4 Graus",
    5: "5 Graus",
    6: "6 Graus",
    7: "7 Graus",
    8: "8 Graus",
    9: "9 Graus",
    10: "10 Graus",
  },
};
