
  create table "public"."graduations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "belt" text,
    "degree" bigint,
    "userId" bigint not null,
    "modality" text
      );


alter table "public"."graduations" enable row level security;

CREATE UNIQUE INDEX graduations_pkey ON public.graduations USING btree (id);

alter table "public"."graduations" add constraint "graduations_pkey" PRIMARY KEY using index "graduations_pkey";

alter table "public"."graduations" add constraint "graduations_userId_fkey" FOREIGN KEY ("userId") REFERENCES public.users(id) not valid;

alter table "public"."graduations" validate constraint "graduations_userId_fkey";

grant delete on table "public"."graduations" to "anon";

grant insert on table "public"."graduations" to "anon";

grant references on table "public"."graduations" to "anon";

grant select on table "public"."graduations" to "anon";

grant trigger on table "public"."graduations" to "anon";

grant truncate on table "public"."graduations" to "anon";

grant update on table "public"."graduations" to "anon";

grant delete on table "public"."graduations" to "authenticated";

grant insert on table "public"."graduations" to "authenticated";

grant references on table "public"."graduations" to "authenticated";

grant select on table "public"."graduations" to "authenticated";

grant trigger on table "public"."graduations" to "authenticated";

grant truncate on table "public"."graduations" to "authenticated";

grant update on table "public"."graduations" to "authenticated";

grant delete on table "public"."graduations" to "service_role";

grant insert on table "public"."graduations" to "service_role";

grant references on table "public"."graduations" to "service_role";

grant select on table "public"."graduations" to "service_role";

grant trigger on table "public"."graduations" to "service_role";

grant truncate on table "public"."graduations" to "service_role";

grant update on table "public"."graduations" to "service_role";


  create policy "Enable delete for authenticated users only"
  on "public"."class"
  as permissive
  for delete
  to authenticated
using (true);



  create policy "Enable update for authenticated users only"
  on "public"."class"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



  create policy "Enable insert for authenticated users only"
  on "public"."graduations"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for all users"
  on "public"."graduations"
  as permissive
  for select
  to public
using (true);



  create policy "Enable update for authenticated users only"
  on "public"."graduations"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



  create policy "Enable update for authenticated users only"
  on "public"."gyms"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



  create policy "Enable update for authenticated users only"
  on "public"."users"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



