
  create table "public"."class" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "description" text,
    "start" time without time zone,
    "end" time without time zone,
    "day" text,
    "gym_id" bigint,
    "created_by" bigint,
    "instructor_id" bigint,
    "modality" text
      );


alter table "public"."class" enable row level security;

CREATE UNIQUE INDEX class_pkey ON public.class USING btree (id);

alter table "public"."class" add constraint "class_pkey" PRIMARY KEY using index "class_pkey";

alter table "public"."class" add constraint "class_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.users(id) not valid;

alter table "public"."class" validate constraint "class_created_by_fkey";

alter table "public"."class" add constraint "class_gym_id_fkey" FOREIGN KEY (gym_id) REFERENCES public.gyms(id) not valid;

alter table "public"."class" validate constraint "class_gym_id_fkey";

alter table "public"."class" add constraint "class_instructor_id_fkey" FOREIGN KEY (instructor_id) REFERENCES public.users(id) not valid;

alter table "public"."class" validate constraint "class_instructor_id_fkey";

grant delete on table "public"."class" to "anon";

grant insert on table "public"."class" to "anon";

grant references on table "public"."class" to "anon";

grant select on table "public"."class" to "anon";

grant trigger on table "public"."class" to "anon";

grant truncate on table "public"."class" to "anon";

grant update on table "public"."class" to "anon";

grant delete on table "public"."class" to "authenticated";

grant insert on table "public"."class" to "authenticated";

grant references on table "public"."class" to "authenticated";

grant select on table "public"."class" to "authenticated";

grant trigger on table "public"."class" to "authenticated";

grant truncate on table "public"."class" to "authenticated";

grant update on table "public"."class" to "authenticated";

grant delete on table "public"."class" to "service_role";

grant insert on table "public"."class" to "service_role";

grant references on table "public"."class" to "service_role";

grant select on table "public"."class" to "service_role";

grant trigger on table "public"."class" to "service_role";

grant truncate on table "public"."class" to "service_role";

grant update on table "public"."class" to "service_role";


  create policy "Enable insert for authenticated users only"
  on "public"."gyms"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for all users"
  on "public"."gyms"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."users"
  as permissive
  for select
  to public
using (true);



