
  create table "public"."versions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "appVersion" text,
    "disabled_at" date
      );


alter table "public"."versions" enable row level security;

CREATE INDEX "versions_appVersion_idx" ON public.versions USING btree ("appVersion") WHERE (disabled_at IS NULL);

CREATE INDEX versions_disabled_at_idx ON public.versions USING btree (disabled_at) WHERE (disabled_at IS NULL);

CREATE UNIQUE INDEX versions_pkey ON public.versions USING btree (id);

alter table "public"."versions" add constraint "versions_pkey" PRIMARY KEY using index "versions_pkey";

grant delete on table "public"."versions" to "anon";

grant insert on table "public"."versions" to "anon";

grant references on table "public"."versions" to "anon";

grant select on table "public"."versions" to "anon";

grant trigger on table "public"."versions" to "anon";

grant truncate on table "public"."versions" to "anon";

grant update on table "public"."versions" to "anon";

grant delete on table "public"."versions" to "authenticated";

grant insert on table "public"."versions" to "authenticated";

grant references on table "public"."versions" to "authenticated";

grant select on table "public"."versions" to "authenticated";

grant trigger on table "public"."versions" to "authenticated";

grant truncate on table "public"."versions" to "authenticated";

grant update on table "public"."versions" to "authenticated";

grant delete on table "public"."versions" to "service_role";

grant insert on table "public"."versions" to "service_role";

grant references on table "public"."versions" to "service_role";

grant select on table "public"."versions" to "service_role";

grant trigger on table "public"."versions" to "service_role";

grant truncate on table "public"."versions" to "service_role";

grant update on table "public"."versions" to "service_role";

  create policy "Enable read access for all users"
  on "public"."versions"
  as permissive
  for select
  to public
using (true);



