
  create table "public"."gyms" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "address" text not null,
    "managerId" bigint not null,
    "logo" text,
    "since" date not null
      );


alter table "public"."gyms" enable row level security;

CREATE UNIQUE INDEX gyms_pkey ON public.gyms USING btree (id);

alter table "public"."gyms" add constraint "gyms_pkey" PRIMARY KEY using index "gyms_pkey";

alter table "public"."gyms" add constraint "gyms_managerId_fkey" FOREIGN KEY ("managerId") REFERENCES public.users(id) not valid;

alter table "public"."gyms" validate constraint "gyms_managerId_fkey";

grant delete on table "public"."gyms" to "anon";

grant insert on table "public"."gyms" to "anon";

grant references on table "public"."gyms" to "anon";

grant select on table "public"."gyms" to "anon";

grant trigger on table "public"."gyms" to "anon";

grant truncate on table "public"."gyms" to "anon";

grant update on table "public"."gyms" to "anon";

grant delete on table "public"."gyms" to "authenticated";

grant insert on table "public"."gyms" to "authenticated";

grant references on table "public"."gyms" to "authenticated";

grant select on table "public"."gyms" to "authenticated";

grant trigger on table "public"."gyms" to "authenticated";

grant truncate on table "public"."gyms" to "authenticated";

grant update on table "public"."gyms" to "authenticated";

grant delete on table "public"."gyms" to "service_role";

grant insert on table "public"."gyms" to "service_role";

grant references on table "public"."gyms" to "service_role";

grant select on table "public"."gyms" to "service_role";

grant trigger on table "public"."gyms" to "service_role";

grant truncate on table "public"."gyms" to "service_role";

grant update on table "public"."gyms" to "service_role";


  create policy "Enable insert for authenticated users only"
  on "public"."users"
  as permissive
  for insert
  to authenticated
with check (true);



