
  create table "public"."checkins" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "userId" bigint,
    "classId" bigint,
    "date" date
      );


alter table "public"."checkins" enable row level security;

CREATE UNIQUE INDEX checkins_pkey ON public.checkins USING btree (id);

alter table "public"."checkins" add constraint "checkins_pkey" PRIMARY KEY using index "checkins_pkey";

alter table "public"."checkins" add constraint "checkins_classId_fkey" FOREIGN KEY ("classId") REFERENCES public.class(id) not valid;

alter table "public"."checkins" validate constraint "checkins_classId_fkey";

alter table "public"."checkins" add constraint "checkins_userId_fkey" FOREIGN KEY ("userId") REFERENCES public.users(id) not valid;

alter table "public"."checkins" validate constraint "checkins_userId_fkey";

grant delete on table "public"."checkins" to "anon";

grant insert on table "public"."checkins" to "anon";

grant references on table "public"."checkins" to "anon";

grant select on table "public"."checkins" to "anon";

grant trigger on table "public"."checkins" to "anon";

grant truncate on table "public"."checkins" to "anon";

grant update on table "public"."checkins" to "anon";

grant delete on table "public"."checkins" to "authenticated";

grant insert on table "public"."checkins" to "authenticated";

grant references on table "public"."checkins" to "authenticated";

grant select on table "public"."checkins" to "authenticated";

grant trigger on table "public"."checkins" to "authenticated";

grant truncate on table "public"."checkins" to "authenticated";

grant update on table "public"."checkins" to "authenticated";

grant delete on table "public"."checkins" to "service_role";

grant insert on table "public"."checkins" to "service_role";

grant references on table "public"."checkins" to "service_role";

grant select on table "public"."checkins" to "service_role";

grant trigger on table "public"."checkins" to "service_role";

grant truncate on table "public"."checkins" to "service_role";

grant update on table "public"."checkins" to "service_role";


  create policy "Enable insert for authenticated users only"
  on "public"."checkins"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for all users"
  on "public"."checkins"
  as permissive
  for select
  to public
using (true);



  create policy "Enable update for authenticated users only"
  on "public"."checkins"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



