
  create table "public"."app_stores" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "store" text,
    "url" text,
    "disabled_at" timestamp with time zone
      );


alter table "public"."app_stores" enable row level security;

CREATE UNIQUE INDEX app_stores_pkey ON public.app_stores USING btree (id);

alter table "public"."app_stores" add constraint "app_stores_pkey" PRIMARY KEY using index "app_stores_pkey";

grant delete on table "public"."app_stores" to "anon";

grant insert on table "public"."app_stores" to "anon";

grant references on table "public"."app_stores" to "anon";

grant select on table "public"."app_stores" to "anon";

grant trigger on table "public"."app_stores" to "anon";

grant truncate on table "public"."app_stores" to "anon";

grant update on table "public"."app_stores" to "anon";

grant delete on table "public"."app_stores" to "authenticated";

grant insert on table "public"."app_stores" to "authenticated";

grant references on table "public"."app_stores" to "authenticated";

grant select on table "public"."app_stores" to "authenticated";

grant trigger on table "public"."app_stores" to "authenticated";

grant truncate on table "public"."app_stores" to "authenticated";

grant update on table "public"."app_stores" to "authenticated";

grant delete on table "public"."app_stores" to "service_role";

grant insert on table "public"."app_stores" to "service_role";

grant references on table "public"."app_stores" to "service_role";

grant select on table "public"."app_stores" to "service_role";

grant trigger on table "public"."app_stores" to "service_role";

grant truncate on table "public"."app_stores" to "service_role";

grant update on table "public"."app_stores" to "service_role";

